services:
  mongodb:
    image: "mongo"
    volumes:
      - db:/data/db
    env_file:
      - ./backend/.env
    environment:
      - MONGO_HOSTNAME=mongodb
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    volumes:
      - ./backend:/app:ro
      - /app/node_modules
      - images:/app/public/images
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
  #
  # frontend:
  #   build: ./frontend
  #   volumes:
  #     - ./frontend/src:/app/src:ro
  #   ports:
  #     - "5173:5173"
  #   stdin_open: true
  #   tty: true
  #   depends_on:
  #     - backend

volumes:
  db:
  images:
