services:
  seeding:
    build:
      context: ./backend
      dockerfile: Dockerfile.seed
    env_file:
      - ./backend/.env
    volumes:
      - public_images:/app/public/images
    depends_on:
      - mongodb
