services:
  mongodb:
    image: "mongo"
    volumes:
      - db:/data/db
    env_file:
      - ./cms/.env.production
    ports:
      - "27017:27017"
    profiles:
      - initial-run
      - run

  seed:
    build:
      context: ./cms
      dockerfile: Dockerfile.seed
    env_file:
      - ./cms/.env.production
    volumes:
      - public_images:/app/public/images
    depends_on:
      - mongodb
    profiles:
      - initial-run

  cms:
    build: ./cms
    volumes:
      - public_images:/app/public/images
    env_file:
      - ./cms/.env.production
    ports:
      - "3000:3000"
    depends_on:
      - seed
    profiles:
      - initial-run
      - run

  client:
    build: ./client
    ports:
      - "8080:80"
    stdin_open: true
    tty: true
    depends_on:
      - cms
    profiles:
      - initial-run
      - run

volumes:
  db:
  public_images:
