services:
  mongodb:
    image: "mongo"
    volumes:
      - db:/data/db
    env_file:
      - ./backend/.env
    ports:
      - "27017:27017" # TODO: Should be removed in production

  seeding:
    build:
      context: ./backend
      dockerfile: Dockerfile.seed
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app:ro
      - /app/node_modules
      - images:/app/public/images
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - seeding

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/src:/app/src:ro
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  db:
  images:
