services:
  mongodb:
    image: "mongo"
    volumes:
      - db:/data/db
    env_file:
      - ./backend/.env.production
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    volumes:
      - ./backend:/app:ro
      - /app/seeds
      - /app/node_modules
      - public_images:/app/public/images
    env_file:
      - ./backend/.env.production
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client/src:/app/src:ro
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  db:
  public_images:
