FROM node:16-alpine

WORKDIR /app

COPY package.json .
RUN npm i

COPY bin/seed.ts bin/
COPY data/seeds/images public/images/
COPY models models/
COPY utils utils/
COPY tsconfig.json .

CMD [ "npm", "run", "seed" ]
